### ISSUE TITLE
Crash Report about DungeonDifficulty to GuardVillagers(Fabric)

### ISSUE THREAD

**Issue by Healock** [ZsoltMolnarrr/PowerScale#21]
GuardVillagers: https://modrinth.com/mod/guard-villagers-(fabricquilt)

```
java.lang.UnsupportedOperationException
	at com.google.common.collect.Multimaps$UnmodifiableMultimap.removeAll(Multimaps.java:757)
	at net.dungeon_difficulty.logic.ItemScaling.applyModifiersForItemStack(ItemScaling.java:237)
	at net.dungeon_difficulty.logic.ItemScaling.scale(ItemScaling.java:84)
	at net.dungeon_difficulty.logic.ItemScaling.scale(ItemScaling.java:71)
	at net.dungeon_difficulty.logic.ItemScaling$1.apply(ItemScaling.java:55)
	at net.dungeon_difficulty.logic.ItemScaling$1.apply(ItemScaling.java:41)
	at net.minecraft.class_117.method_514(class_117.java:14)
	at net.minecraft.class_117.method_514(class_117.java:14)
	at net.minecraft.class_117.method_514(class_117.java:14)
	at net.minecraft.class_77.method_433(class_77.java:33)
	at net.minecraft.class_85$1.method_426(class_85.java:59)
	at net.minecraft.class_55.method_345(class_55.java:81)
	at net.minecraft.class_55.method_341(class_55.java:96)
	at net.minecraft.class_52.method_328(class_52.java:86)
	at net.minecraft.class_52.method_320(class_52.java:103)
	at net.minecraft.class_52.method_319(class_52.java:116)
	at net.minecraft.class_52.method_51878(class_52.java:111)
	at dev.sterner.guardvillagers.common.entity.GuardEntity.getStacksFromLootTable(GuardEntity.java:570)
	at dev.sterner.guardvillagers.common.entity.GuardEntity.method_6007(GuardEntity.java:444)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at dev.sterner.guardvillagers.common.entity.GuardEntity.method_5773(GuardEntity.java:458)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
[crash-2024-01-21_17.37.07-server.txt](https://github.com/ZsoltMolnarrr/DungeonDifficulty/files/14000750/crash-2024-01-21_17.37.07-server.txt)

**Comment by ZsoltMolnarrr** [comment]
This issue never occured for me, despite using Dungeon Difficulty and Guard Villagers together.
Please specify how exactly to reproduce this issue, with the **absolute minimum** number of mods present.

**Comment by Healock** [comment]
> This issue never occured for me, despite using Dungeon Difficulty and Guard Villagers together. Please specify how exactly to reproduce this issue, with the **absolute minimum** number of mods present.

When the server loads a large number of chunks, it directly generates the following error and crashes the server. I don't know how to reproduce it stably at the moment.

**Comment by BradClc** [comment]
same issue for me. But when you only have guard and dungeondifficulty it would not happen. If you add it in your modpack, enter a large modded redesigned village (with a lot of entities), it immediately crash.

**Comment by ZsoltMolnarrr** [comment]
I am still unable to reproduce this issue.
